require "user.beautiful"
require "user.options"
require "user.plugins"
require "user.remaps"
require "user.toggleterm"
require "user.lspinit"
require "user.treesitter"
require "user.coderunner"
require "user.debugger"

